# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3afb09a1d3616cc8e3ffa4d8cc0aa8ee75c476f2df9c8b3ae8243e858657a16d44be6b8beb3271d0cbb2b305cd777ad2fc80bfbe1b11dbce9a5be37f181348ea

test:
  secret_key_base: 096a333bed19e7974f22879da865d9d954fdb4bbd8fd9bf7156c8881996180b69da62a426e4714a97a0765938bde4d5272e749476c67706311441879983a8e3d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
